apiVersion: apps/v1
kind: Deployment
metadata:
  name: betteruptime-worker-ap-southeast-1
  namespace: betteruptime
spec:
  replicas: 3
  selector:
    matchLabels:
      app: betteruptime-worker
      region: ap-southeast-1
  template:
    metadata:
      labels:
        app: betteruptime-worker
        region: ap-southeast-1
    spec:
      containers:
        - name: worker
          image: adi1308/betteruptime-worker:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: betteruptime-secrets
                  key: DATABASE_URL
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  name: betteruptime-secrets
                  key: REDIS_ADDR
            - name: REGION_ID
              value: "ap-southeast-1"
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Unique per pod
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
