apiVersion: v1
kind: Secret
metadata:
  name: betteruptime-secrets
  namespace: betteruptime
type: Opaque
data:
  DATABASE_URL: <base64-encoded-postgres-url> # e.g., cG9zdGdyZXM6Ly91c2VyOnBhc3NAaG9zdC9kYj9zc2xtb2RlPXJlcXVpcmU=
  REDIS_ADDR: <base64-encoded-redis-url> # e.g., cmVkaXM6Ly91c2VyOnBhc3NAaG9zdDo2Mzc5
